title: 8 Club
description: >- # this means to ignore newlines until "baseurl:"
  ANON JETTON created by closed community (8 club)
# baseurl: "" # the subpath of your site, e.g. /blog
url: "https://club8-devs.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

plugins:
  - jekyll-remote-theme

remote_theme: jekyll/minima

header_pages:
    - index.markdown
    - index_en.markdown

minima:
  skin: dark
  social_links:
    - platform: telegram
      user_url: https://t.me/anon_club
    - platform: twitter
      user_url: https://x.com/anonclub8
    - platform: github
      user_url: https://github.com/club8-devs
# plugins:
#   - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
